---
- name: Install nginx redhat
  yum: name=nginx state=present
  when: ansible_os_family == "RedHat"

- name: copy template  redhat
  template: src=default dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  when: ansible_os_family == "RedHat"
  
- name: Install nginx debian
  apt: pkg=nginx state=installed
  when: ansible_os_family == "Debian"

- name: copy template debian
  template: src=default dest=/etc/nginx/sites-enabled/default
  notify: restart nginx
  when: ansible_os_family == "Debian"

- name: create directory
  file: path=/var/www/html state=directory mode=0751

- name: Deploy content
  get_url: url=https://raw.githubusercontent.com/puppetlabs/exercise-webpage/master/index.html dest=/var/www/html/
